- hosts: localhost
  tasks:
    - name: Setting up Security/Firewall Group
      ec2_group:
         name: shahab_AWS_Security_Grp
         description: Rules Allowing Traffic on port 22 and 80
         region: us-east-2
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
         rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Provision a EC2 Instance
      ec2:
         key_name: ohio
         region: us-east-2
         instance_type: t2.micro
         image: ami-25615740
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
           Name: awslabserver
           Owner: shahabzd
         volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 8
         monitoring: no
         vpc_subnet_id: subnet-9eb9ffd3
         assign_public_ip: yes
         group: shahab_AWS_Security_Grp
      register: ec2_out

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'
